# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170928_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dead',
            field=models.BooleanField(default=False),
        ),
    ]
