# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
